/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.pascal.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.pascal.PascalRuntimeModule;
import org.xtext.example.pascal.PascalStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PascalIdeSetup extends PascalStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PascalRuntimeModule(), new PascalIdeModule()));
	}
	
}
