/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.pascal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PascalUiModule extends AbstractPascalUiModule {

	public PascalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
