/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.pascal;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PascalStandaloneSetup extends PascalStandaloneSetupGenerated {

	public static void doSetup() {
		new PascalStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
